name: Expo Build
on:
  push:
    branches:
      - 18-configure-cicd

jobs:
  build:
    name: Build and Optimize
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
      - name: Install dependencies
        run: yarn install
      - name: Optimizeexpo
        run: npx expo-optimize
      - name: Build project for production
        run: expo build:web
